'use strict';
const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../public');
const results=path.resolve(__dirname,'../validation/product');fs.mkdirSync(results,{recursive:true});
const me={id:'alice',nickname:'Алекс',friends:['bob','carol'],friendRequests:[],blockedUsers:[],status:'На связи'};
const bob={id:'bob',nickname:'Макс',friends:['alice'],friendRequests:[],blockedUsers:[],online:true};
const carol={...bob,id:'carol',nickname:'Саша',online:false};
const group={id:'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',name:'Планы на выходные',ownerId:'alice',members:[me,bob,carol]};
const mock=`window.__sent=[];window.__response={ok:true,status:'pending'};window.__connections=0;window.io=function(){const handlers={};const s={connected:false,auth:null,on(e,f){(handlers[e]??=[]).push(f);return s},off(){return s},fire(e,p){for(const f of handlers[e]||[])f(p)},connect(){s.connected=true;window.__connections++;setTimeout(()=>{s.fire('connect');s.fire('profile',${JSON.stringify(me)})},10);return s},disconnect(){s.connected=false;return s},emit(e,p,cb){window.__sent.push({event:e,payload:p});if(cb)setTimeout(()=>cb(null,window.__response),window.__ackDelay||30);return s},timeout(){return s},io:{on(){}}};window.__socket=s;return s}`;
const server=http.createServer((req,res)=>{let name=new URL(req.url,'http://local').pathname;if(name==='/socket.io/socket.io.js'){res.setHeader('Content-Type','text/javascript');return res.end(mock)}if(name==='/')name='/index.html';const file=path.join(root,name);if(!file.startsWith(root+path.sep)){res.statusCode=403;return res.end()}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.ttf')?'font/ttf':'text/html');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; script-src-attr 'none'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self'; object-src 'none'");fs.readFile(file,(e,data)=>{if(e){res.statusCode=404;res.end('not found')}else res.end(data)})});
const tests=[];async function check(name,fn){await fn();tests.push(name);console.log('PASS',name)}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{}),args:['--no-sandbox']});
 try{
 const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());let data={};if(['/api/login','/api/register'].includes(u.pathname))data={user:me,token:'test-token'};else if(u.pathname==='/api/me')data=me;else if(u.pathname==='/api/groups')data=[group];else if(u.pathname.startsWith('/api/profile/'))data=u.pathname.endsWith('bob')?bob:carol;else if(u.pathname.includes('/messages'))data=[];await route.fulfill({json:data});});
 await page.goto(origin);await page.waitForLoadState('load');await page.fill('#login-id','alice');await page.fill('#login-pw','password123');await page.click('#btn-login');await page.waitForSelector('#app-screen.active');await page.waitForTimeout(180);
 for(const width of [320,390,640,768,1024,1440]){
  await page.setViewportSize({width,height:844});await page.evaluate(()=>openGroupChat('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'));await page.waitForTimeout(70);await page.fill('#group-msg-input','Сообщение');
  await check(`Group composer and controls fit ${width}px`,async()=>{const input=await page.locator('#group-msg-input').boundingBox(),send=await page.locator('#btn-group-send').boundingBox(),member=await page.locator('#btn-toggle-members').boundingBox();assert.ok(input.width>=55);assert.ok(send.x+send.width<=width);assert.ok(send.y+send.height<=845);assert.ok(member.x+member.width<=width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);});
  if(width===768){await page.click('#btn-toggle-members');await check('Tablet members control opens a visible panel',async()=>assert.equal(await page.locator('#group-members-panel').isVisible(),true));await page.keyboard.press('Escape');}
 }
 await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>productUI.showFriendsPage('all'));
 await page.evaluate(()=>switchSidebarTab('groups'));await check('Create group affordance is visible without hover',async()=>{assert.equal(await page.locator('#btn-create-group').isVisible(),true);assert.equal(await page.locator('#btn-create-group').evaluate(e=>getComputedStyle(e).opacity),'1');});
 await page.click('#btn-create-group');await check('Original create group dialog opens',async()=>assert.equal(await page.locator('#create-group-modal').isVisible(),true));await page.keyboard.press('Escape');
 await page.evaluate(()=>openChat('bob'));await page.waitForTimeout(70);await page.fill('#msg-input','Первая строка');await page.keyboard.press('Shift+Enter');await page.keyboard.type('Вторая строка');await check('Shift+Enter preserves actual newline',async()=>assert.equal(await page.inputValue('#msg-input'),'Первая строка\nВторая строка'));
 await page.evaluate(()=>{__ackDelay=500;__response={ok:true};});await page.click('#btn-send');await page.evaluate(()=>openChat('carol'));await page.waitForTimeout(70);await page.fill('#msg-input','Другому другу');await check('In-flight message does not lock another DM',async()=>assert.equal(await page.locator('#btn-send').isEnabled(),true));await page.click('#btn-send');await page.waitForTimeout(600);await check('Independent messages both get acknowledged',async()=>assert.equal(await page.inputValue('#msg-input'),''));
 await page.evaluate(()=>openChat('bob'));await page.waitForTimeout(70);await page.fill('#msg-input','Отправляемое');await page.click('#btn-send');await page.fill('#msg-input','Следующий черновик');await page.waitForTimeout(600);await check('New text is preserved during previous acknowledgement',async()=>assert.equal(await page.inputValue('#msg-input'),'Следующий черновик'));
 await page.evaluate(()=>{__socket.connected=false;});await page.click('#btn-send');await check('Disconnected send keeps draft intact',async()=>assert.equal(await page.inputValue('#msg-input'),'Следующий черновик'));await page.evaluate(()=>__socket.connected=true);
 await page.evaluate(()=>productUI.hideDm('bob'));await page.reload();await page.waitForTimeout(300);await check('Hidden DM persists after reload without losing the friend',async()=>{assert.equal(await page.locator('[data-fid="bob"]').count(),0);assert.equal(await page.evaluate(()=>!!state.friends.bob),true);});
 await page.evaluate(()=>{state.unread.bob=1;refreshFriendItem('bob');});await check('New unread message restores a hidden conversation',async()=>assert.equal(await page.locator('[data-fid="bob"]').count(),1));
 await page.evaluate(()=>productUI.showFriendsPage('all'));
 await page.evaluate(fs.readFileSync(require.resolve('axe-core'),'utf8'));
 const audit=await page.evaluate(async()=>axe.run({include:[['.sidebar'],['.friends-page']]},{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}}));
 fs.writeFileSync(path.join(results,'accessibility.json'),JSON.stringify(audit.violations.map(v=>({id:v.id,impact:v.impact,description:v.description,nodes:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),null,2));
 await check('No serious/critical structural accessibility violations in new Friends UI',async()=>{const failures=audit.violations.filter(v=>['serious','critical'].includes(v.impact)&&v.id!=='color-contrast');assert.deepEqual(failures.map(v=>v.id),[]);});
 const authPage=await browser.newPage({viewport:{width:390,height:480}});await authPage.goto(origin);await authPage.waitForLoadState('load');await authPage.click('[data-action="0"]');await authPage.locator('#btn-register').scrollIntoViewIfNeeded();await check('Registration remains reachable on short screens',async()=>{const b=await authPage.locator('#btn-register').boundingBox();assert.ok(b.y>=0&&b.y+b.height<=481);});await authPage.close();
 await page.emulateMedia({reducedMotion:'reduce'});await check('Reduced-motion preference is respected',async()=>assert.equal(await page.locator('.sidebar-tab').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s'));
 await check('No runtime exceptions in edge cases',async()=>assert.deepEqual(errors,[]));
 fs.writeFileSync(path.join(results,'edge-results.json'),JSON.stringify({passed:tests.length,tests,note:'Mocked transport. Palette contrasts are reported separately because the requested exact Discord colors are retained.'},null,2));console.log(JSON.stringify({passed:tests.length},null,2));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
